"""
docx_export.py — Professional Word Document Export

Turns any council task's final output into a formatted, client-ready
.docx file. Built primarily for the Grant Council so proposal sections
can be downloaded and manually submitted to EU portals (Horizon Europe,
Funding & Tenders, etc.), but works for any council's output.

No external API required — pure python-docx, already a dependency.
"""

from __future__ import annotations

import io
import re
from datetime import datetime, timezone

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor, Inches

COUNCIL_TITLES = {
    "grant": "Grant Proposal",
    "sales": "Sales Outreach Draft",
    "content": "Content Draft",
    "strategy": "Strategy Brief",
    "support": "Support Response",
}

BRAND_COLOR = RGBColor(0x18, 0x18, 0x1B)  # zinc-900, matches dashboard


def _add_heading(doc: Document, text: str, size: int, color: RGBColor = BRAND_COLOR, bold: bool = True):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color
    return p


def _render_body(doc: Document, text: str):
    """
    Render final_output text into the document. Recognizes simple markdown-style
    section markers (### Heading, **bold**, - bullets) so AI-generated structured
    text renders as a real formatted document rather than one flat paragraph.
    """
    lines = text.replace("\r\n", "\n").split("\n")
    for raw_line in lines:
        line = raw_line.rstrip()
        stripped = line.strip()

        if not stripped:
            doc.add_paragraph()
            continue

        heading_match = re.match(r"^#{1,4}\s+(.*)", stripped)
        if heading_match:
            _add_heading(doc, heading_match.group(1), size=13)
            continue

        bullet_match = re.match(r"^[-*•]\s+(.*)", stripped)
        if bullet_match:
            doc.add_paragraph(bullet_match.group(1), style="List Bullet")
            continue

        numbered_match = re.match(r"^\d+[.)]\s+(.*)", stripped)
        if numbered_match:
            doc.add_paragraph(numbered_match.group(1), style="List Number")
            continue

        p = doc.add_paragraph()
        # Render **bold** inline spans without leaking asterisks into the text.
        segments = re.split(r"(\*\*[^*]+\*\*)", stripped)
        for seg in segments:
            if seg.startswith("**") and seg.endswith("**"):
                run = p.add_run(seg[2:-2])
                run.bold = True
            else:
                run = p.add_run(seg)
            run.font.size = Pt(11)


def build_task_docx(task: dict) -> bytes:
    """
    Build a formatted .docx for a task and return the raw file bytes.
    """
    doc = Document()

    section = doc.sections[0]
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)

    council = (task.get("council") or "").lower()
    title = COUNCIL_TITLES.get(council, "AI Council OS Output")

    header = doc.add_paragraph()
    header.alignment = WD_ALIGN_PARAGRAPH.LEFT
    header_run = header.add_run("AI Council OS")
    header_run.font.size = Pt(10)
    header_run.font.color.rgb = RGBColor(0x71, 0x71, 0x7A)  # zinc-500

    _add_heading(doc, title, size=22)

    subtitle = task.get("task_description", "")[:200]
    if subtitle:
        sp = doc.add_paragraph()
        sr = sp.add_run(subtitle)
        sr.font.size = Pt(11)
        sr.font.color.rgb = RGBColor(0x52, 0x52, 0x5B)  # zinc-600
        sr.italic = True

    meta = doc.add_paragraph()
    meta_run = meta.add_run(
        f"Confidence: {task.get('confidence_score', 0):.0f}/100   |   "
        f"Task ID: {task.get('task_id', '')}   |   "
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
    )
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(0xA1, 0xA1, 0xAA)  # zinc-400

    doc.add_paragraph()  # spacer
    _add_heading(doc, "Content", size=14)

    final_output = task.get("final_output", "") or "(No final output generated yet.)"
    _render_body(doc, final_output)

    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer_run = footer.add_run(
        "Generated by AI Council OS. This is an AI-drafted document reviewed through a "
        "multi-agent debate process. A human operator must review and approve before external use."
    )
    footer_run.font.size = Pt(8)
    footer_run.italic = True
    footer_run.font.color.rgb = RGBColor(0xA1, 0xA1, 0xAA)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def build_task_docx_filename(task: dict) -> str:
    council = (task.get("council") or "task").lower()
    task_id = task.get("task_id", "output")
    safe_id = re.sub(r"[^a-zA-Z0-9_-]", "", str(task_id))
    return f"{council}-{safe_id}.docx"
